<?php
//Este archivo instala los datos del mapa para la variante Guerra Civil Espa�ola
// This is file installs the map data for the Guerra Civil Espa�ola variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");


InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Finisterre', 'Sea', 'No', 330, 200, 133, 93, 'Neutral'),
	array('Atlantico Norte', 'Sea', 'No', 330, 450, 130, 170, 'Neutral'),
	array('Tenerife', 'Coast', 'Yes', 148, 1028, 58, 413, 'Neutral'),
	array('Fuerteventura', 'Coast', 'Yes', 352, 1006, 140, 400, 'Nacional'),
	array('Atlantico Sur', 'Sea', 'No', 520, 990, 210, 380, 'Neutral'),
	array('Estrecho de Gibraltar', 'Sea', 'No', 619, 964, 246, 387, 'Neutral'),
	array('Mediterraneo Sur', 'Sea', 'No', 940, 980, 340, 390, 'Neutral'),
	array('Levante', 'Sea', 'No', 1190, 700, 465, 275, 'Neutral'),
	array('Costa Catalana', 'Sea', 'No', 1240, 510, 490, 210, 'Neutral'),
	array('Mediterraneo Norte', 'Sea', 'No', 1410, 460, 560, 185, 'Neutral'),
	array('Golfo de Vizcaya', 'Sea', 'No', 920, 165, 375, 60, 'Neutral'),
	array('Cantabrico', 'Sea', 'No', 710, 140, 190, 35, 'Neutral'),
	array('Ceuta', 'Coast', 'Yes', 660, 990, 260, 400, 'Africano'),
	array('Marruecos', 'Coast', 'No', 740, 1075, 270, 440, 'Africano'),
	array('Melilla', 'Coast', 'Yes', 860, 1035, 340, 415, 'Africano'),
	array('Mallorca', 'Coast', 'Yes', 1310, 580, 520, 230, 'Neutral'),
	array('La Coruna', 'Coast', 'Yes', 450, 180, 178, 72, 'Sublevado'),
	array('Pontevedra', 'Coast', 'Yes', 425, 270, 170, 115, 'Sublevado'),
	array('Lugo', 'Coast', 'Yes', 510, 210, 205, 90, 'Neutral'),
	array('Orense', 'Land', 'Yes', 500, 300, 195, 115, 'Sublevado'),
	array('Oviedo', 'Coast', 'Yes', 615, 180, 250, 70, 'Popular'),
	array('Leon', 'Land', 'Yes', 645, 245, 260, 105, 'Neutral'),
	array('Zamora', 'Land', 'No', 640, 370, 260, 150, 'Nacional'),
	array('Salamanca', 'Land', 'Yes', 650, 430, 260, 175, 'Nacional'),
	array('Caceres', 'Land', 'Yes', 600, 600, 240, 240, 'Neutral'),
	array('Badajoz', 'Land', 'Yes', 600, 690, 240, 270, 'Republica'),
	array('Huelva', 'Coast', 'Yes', 550, 815, 220, 330, 'Neutral'),
	array('Santander', 'Coast', 'Yes', 790, 170, 315, 70, 'Popular'),
	array('Bilbao', 'Coast', 'Yes', 870, 170, 350, 70, 'Popular'),
	array('Donostia', 'Coast', 'No', 925, 190, 370, 75, 'Republica'),
	array('Palencia', 'Land', 'No', 735, 270, 290, 110, 'Nacional'),
	array('Burgos', 'Land', 'Yes', 800, 270, 320, 115, 'Neutral'),
	array('Vitoria', 'Land', 'Yes', 890, 250, 355, 100, 'Neutral'),
	array('Logrono', 'Land', 'No', 895, 285, 368, 118, 'Nacional'),
	array('Pamplona', 'Land', 'Yes', 970, 230, 390, 95, 'Neutral'),
	array('Huesca', 'Land', 'Yes', 1090, 330, 435, 130, 'Falange'),
	array('Lerida', 'Land', 'No', 1180, 330, 470, 120, 'Republica'),
	array('Barcelona', 'Coast', 'Yes', 1250, 350, 495, 155, 'Milicias'),
	array('Gerona', 'Coast', 'Yes', 1310, 340, 525, 135, 'Milicias'),
	array('Valladolid', 'Land', 'Yes', 730, 380, 290, 145, 'Nacional'),
	array('Segovia', 'Land', 'No', 765, 435, 305, 175, 'Nacional'),
	array('Soria', 'Land', 'Yes', 890, 380, 355, 155, 'Falange'),
	array('Zaragoza', 'Land', 'Yes', 1000, 360, 405, 145, 'Falange'),
	array('Tarragona', 'Coast', 'Yes', 1135, 440, 472, 162, 'Milicias'),
	array('Avila', 'Land', 'Yes', 720, 460, 290, 185, 'Neutral'),
	array('Madrid', 'Land', 'Yes', 830, 515, 330, 200, 'Republica'),
	array('Guadalajara', 'Land', 'Yes', 875, 465, 350, 185, 'Neutral'),
	array('Teruel', 'Land', 'No', 1010, 460, 400, 200, 'Nacional'),
	array('Castellon', 'Coast', 'No', 1080, 530, 430, 210, 'Republica'),
	array('Toledo', 'Land', 'Yes', 780, 570, 310, 230, 'Republica'),
	array('Cuenca', 'Land', 'Yes', 920, 570, 370, 230, 'Neutral'),
	array('Valencia', 'Coast', 'Yes', 1030, 630, 420, 250, 'Neutral'),
	array('Ciudad Real', 'Land', 'No', 800, 640, 330, 260, 'Republica'),
	array('Albacete', 'Land', 'Yes', 940, 680, 380, 260, 'Brigadas'),
	array('Alicante', 'Coast', 'No', 1040, 710, 410, 290, 'Republica'),
	array('Cordoba', 'Land', 'Yes', 720, 760, 290, 300, 'Neutral'),
	array('Jaen', 'Land', 'Yes', 820, 735, 320, 310, 'Neutral'),
	array('Murcia', 'Coast', 'Yes', 980, 740, 400, 310, 'Brigadas'),
	array('Sevilla', 'Land', 'No', 650, 800, 260, 315, 'Republica'),
	array('Cadiz', 'Coast', 'Yes', 640, 915, 255, 365, 'Africano'),
	array('Malaga', 'Coast', 'Yes', 720, 890, 290, 355, 'Neutral'),
	array('Granada', 'Coast', 'No', 820, 820, 330, 330, 'Republica'),
	array('Almeria', 'Coast', 'Yes', 920, 820, 370, 340, 'Brigadas'),
	array('Argelia', 'Sea', 'No', 1200, 910, 480, 360, 'Neutral'),
	array('Portugal', 'Sea', 'No', 375, 615, 160, 260, 'Neutral'),
	array('Francia Costa Oeste', 'Sea', 'No', 1000, 100, 400, 40, 'Neutral'),
	array('Francia Costa Este', 'Sea', 'No', 1325, 200, 540, 70, 'Neutral')
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $country)=$territoryRawRow;
	if( $country=='Neutral' )
		$countryID=0;
	else
		$countryID=$this->countryID($country);
		
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);
$bordersRawData=array(
	//array('Desde','hacia','flotas','ejercitos'),
	array('Finisterre','Cantabrico','Yes','No'),
	array('Finisterre','La Coruna','Yes','No'),
	array('Finisterre','Pontevedra','Yes','No'),
	array('Finisterre','Atlantico Norte','Yes','No'),
	array('Atlantico Norte','Finisterre','Yes','No'),
	array('Atlantico Norte','Atlantico Sur','Yes','No'),
	array('Atlantico Norte','Pontevedra','Yes','No'),
	array('Atlantico Norte','Portugal','Yes','No'),
	array('Atlantico Norte','Tenerife','Yes','No'),
	array('Atlantico Norte','Fuerteventura','Yes','No'),
	array('Tenerife','Atlantico Norte','Yes','No'),
	array('Tenerife','Atlantico Sur','Yes','No'),
	array('Fuerteventura','Atlantico Norte','Yes','No'),
	array('Fuerteventura','Atlantico Sur','Yes','No'),
	array('Atlantico Sur','Atlantico Norte','Yes','No'),
	array('Atlantico Sur','Tenerife','Yes','No'),
	array('Atlantico Sur','Fuerteventura','Yes','No'),
	array('Atlantico Sur','Estrecho de Gibraltar','Yes','No'),
	array('Atlantico Sur','Ceuta','Yes','No'),
	array('Atlantico Sur','Marruecos','Yes','No'),
	array('Atlantico Sur','Huelva','Yes','No'),
	array('Atlantico Sur','Cadiz','Yes','No'),
	array('Atlantico Sur','Portugal','Yes','No'),
	array('Estrecho de Gibraltar','Cadiz','Yes','No'),
	array('Estrecho de Gibraltar','Ceuta','Yes','No'),
	array('Estrecho de Gibraltar','Atlantico Sur','Yes','No'),
	array('Estrecho de Gibraltar','Mediterraneo Sur','Yes','No'),
	array('Mediterraneo Sur','Cadiz','Yes','No'),
	array('Mediterraneo Sur','Estrecho de Gibraltar','Yes','No'),
	array('Mediterraneo Sur','Ceuta','Yes','No'),
	array('Mediterraneo Sur','Melilla','Yes','No'),
	array('Mediterraneo Sur','Argelia','Yes','No'),
	array('Mediterraneo Sur','Malaga','Yes','No'),
	array('Mediterraneo Sur','Granada','Yes','No'),
	array('Mediterraneo Sur','Almeria','Yes','No'),
	array('Mediterraneo Sur','Murcia','Yes','No'),
	array('Mediterraneo Sur','Alicante','Yes','No'),
	array('Mediterraneo Sur','Levante','Yes','No'),
	array('Levante','Mediterraneo Sur','Yes','No'),
	array('Levante','Costa Catalana','Yes','No'),
	array('Levante','Mediterraneo Norte','Yes','No'),
	array('Levante','Argelia','Yes','No'),
	array('Levante','Mallorca','Yes','No'),
	array('Levante','Alicante','Yes','No'),
	array('Levante','Valencia','Yes','No'),
	array('Levante','Castellon','Yes','No'),
	array('Costa Catalana','Castellon','Yes','No'),
	array('Costa Catalana','Levante','Yes','No'),
	array('Costa Catalana','Mediterraneo Norte','Yes','No'),
	array('Costa Catalana','Mallorca','Yes','No'),
	array('Costa Catalana','Tarragona','Yes','No'),
	array('Costa Catalana','Barcelona','Yes','No'),
	array('Costa Catalana','Gerona','Yes','No'),
	array('Mediterraneo Norte','Costa Catalana','Yes','No'),
	array('Mediterraneo Norte','Levante','Yes','No'),
	array('Mediterraneo Norte','Mallorca','Yes','No'),
	array('Mediterraneo Norte','Gerona','Yes','No'),
	array('Mediterraneo Norte','Francia Costa Este','Yes','No'),
	array('Golfo de Vizcaya','Francia Costa Oeste','Yes','No'),
	array('Golfo de Vizcaya','Donostia','Yes','No'),
	array('Golfo de Vizcaya','Bilbao','Yes','No'),
	array('Golfo de Vizcaya','Santander','Yes','No'),
	array('Golfo de Vizcaya','Cantabrico','Yes','No'),
	array('Cantabrico','Golfo de Vizcaya','Yes','No'),
	array('Cantabrico','Santander','Yes','No'),
	array('Cantabrico','Oviedo','Yes','No'),
	array('Cantabrico','Lugo','Yes','No'),
	array('Cantabrico','La Coruna','Yes','No'),
	array('Cantabrico','Francia Costa Oeste','Yes','No'),
	array('Ceuta','Estrecho de Gibraltar','Yes','No'),
	array('Ceuta','Melilla','Yes','Yes'),
	array('Ceuta','Marruecos','Yes','Yes'),
	array('Ceuta','Atlantico Sur','Yes','No'),
	array('Ceuta','Mediterraneo Sur','Yes','No'),
	array('Marruecos','Ceuta','Yes','Yes'),
	array('Marruecos','Melilla','No','Yes'),
	array('Marruecos','Atlantico Sur','Yes','No'),
	array('Melilla','Ceuta','Yes','Yes'),
	array('Melilla','Marruecos','No','Yes'),
	array('Melilla','Argelia','Yes','No'),
	array('Melilla','Mediterraneo Sur','Yes','No'),
	array('Mallorca','Levante','Yes','No'),
	array('Mallorca','Mediterraneo Norte','Yes','No'),
	array('Mallorca','Costa Catalana','Yes','No'),
	array('La Coruna','Cantabrico','Yes','No'),
	array('La Coruna','Finisterre','Yes','No'),
	array('La Coruna','Lugo','Yes','Yes'),
	array('La Coruna','Pontevedra','Yes','Yes'),
	array('Pontevedra','La Coruna','Yes','Yes'),
	array('Pontevedra','Atlantico Norte','Yes','No'),
	array('Pontevedra','Finisterre','Yes','No'),
	array('Pontevedra','Portugal','Yes','No'),
	array('Pontevedra','Orense','No','Yes'),
	array('Pontevedra','Lugo','No','Yes'),
	array('Lugo','Pontevedra','No','Yes'),
	array('Lugo','Cantabrico','Yes','No'),
	array('Lugo','Oviedo','Yes','Yes'),
	array('Lugo','Leon','No','Yes'),
	array('Lugo','Orense','No','Yes'),
	array('Lugo','La Coruna','Yes','Yes'),
	array('Orense','Pontevedra','No','Yes'),
	array('Orense','Lugo','No','Yes'),
	array('Orense','Leon','No','Yes'),
	array('Orense','Zamora','No','Yes'),
	array('Oviedo','Cantabrico','Yes','No'),
	array('Oviedo','Santander','Yes','Yes'),
	array('Oviedo','Lugo','Yes','Yes'),
	array('Oviedo','Leon','No','Yes'),
	array('Leon','Oviedo','No','Yes'),
	array('Leon','Santander','No','Yes'),
	array('Leon','Palencia','No','Yes'),
	array('Leon','Valladolid','No','Yes'),
	array('Leon','Zamora','No','Yes'),
	array('Leon','Orense','No','Yes'),
	array('Leon','Lugo','No','Yes'),
	array('Zamora','Orense','No','Yes'),
	array('Zamora','Leon','No','Yes'),
	array('Zamora','Valladolid','No','Yes'),
	array('Zamora','Salamanca','No','Yes'),
	array('Salamanca','Zamora','No','Yes'),
	array('Salamanca','Valladolid','No','Yes'),
	array('Salamanca','Avila','No','Yes'),
	array('Salamanca','Caceres','No','Yes'),
	array('Caceres','Salamanca','No','Yes'),
	array('Caceres','Avila','No','Yes'),
	array('Caceres','Toledo','No','Yes'),
	array('Caceres','Badajoz','No','Yes'),
	array('Badajoz','Caceres','No','Yes'),
	array('Badajoz','Toledo','No','Yes'),
	array('Badajoz','Ciudad Real','No','Yes'),
	array('Badajoz','Cordoba','No','Yes'),
	array('Badajoz','Sevilla','No','Yes'),
	array('Badajoz','Huelva','No','Yes'),
	array('Huelva','Badajoz','No','Yes'),
	array('Huelva','Sevilla','No','Yes'),
	array('Huelva','Cadiz','Yes','Yes'),
	array('Huelva','Portugal','Yes','No'),
	array('Huelva','Atlantico Sur','Yes','No'),
	array('Santander','Cantabrico','Yes','No'),
	array('Santander','Golfo de Vizcaya','Yes','No'),
	array('Santander','Oviedo','Yes','Yes'),
	array('Santander','Bilbao','Yes','Yes'),
	array('Santander','Leon','No','Yes'),
	array('Santander','Palencia','No','Yes'),
	array('Santander','Burgos','No','Yes'),
	array('Bilbao','Golfo de Vizcaya','Yes','No'),
	array('Bilbao','Santander','Yes','Yes'),
	array('Bilbao','Donostia','Yes','Yes'),
	array('Bilbao','Burgos','No','Yes'),
	array('Bilbao','Vitoria','No','Yes'),
	array('Donostia','Golfo de Vizcaya','Yes','No'),
	array('Donostia','Francia Costa Oeste','Yes','No'),
	array('Donostia','Pamplona','No','Yes'),
	array('Donostia','Vitoria','No','Yes'),
	array('Donostia','Bilbao','Yes','Yes'),
	array('Palencia','Santander','No','Yes'),
	array('Palencia','Burgos','No','Yes'),
	array('Palencia','Valladolid','No','Yes'),
	array('Palencia','Leon','No','Yes'),
	array('Burgos','Santander','No','Yes'),
	array('Burgos','Bilbao','No','Yes'),
	array('Burgos','Vitoria','No','Yes'),
	array('Burgos','Logrono','No','Yes'),
	array('Burgos','Soria','No','Yes'),
	array('Burgos','Segovia','No','Yes'),
	array('Burgos','Valladolid','No','Yes'),
	array('Burgos','Palencia','No','Yes'),
	array('Vitoria','Bilbao','No','Yes'),
	array('Vitoria','Donostia','No','Yes'),
	array('Vitoria','Pamplona','No','Yes'),
	array('Vitoria','Logrono','No','Yes'),
	array('Vitoria','Burgos','No','Yes'),
	array('Logrono','Vitoria','No','Yes'),
	array('Logrono','Pamplona','No','Yes'),
	array('Logrono','Soria','No','Yes'),
	array('Logrono','Burgos','No','Yes'),
	array('Pamplona','Donostia','No','Yes'),
	array('Pamplona','Vitoria','No','Yes'),
	array('Pamplona','Logrono','No','Yes'),
	array('Pamplona','Soria','No','Yes'),
	array('Pamplona','Zaragoza','No','Yes'),
	array('Pamplona','Huesca','No','Yes'),
	array('Huesca','Pamplona','No','Yes'),
	array('Huesca','Zaragoza','No','Yes'),
	array('Huesca','Lerida','No','Yes'),
	array('Lerida','Gerona','No','Yes'),
	array('Lerida','Barcelona','No','Yes'),
	array('Lerida','Tarragona','No','Yes'),
	array('Lerida','Zaragoza','No','Yes'),
	array('Lerida','Huesca','No','Yes'),
	array('Barcelona','Gerona','Yes','Yes'),
	array('Barcelona','Tarragona','Yes','Yes'),
	array('Barcelona','Lerida','No','Yes'),
	array('Barcelona','Costa Catalana','Yes','No'),
	array('Gerona','Costa Catalana','Yes','No'),
	array('Gerona','Mediterraneo Norte','Yes','No'),
	array('Gerona','Francia Costa Este','Yes','No'),
	array('Gerona','Barcelona','Yes','Yes'),
	array('Gerona','Lerida','No','Yes'),
	array('Valladolid','Palencia','No','Yes'),
	array('Valladolid','Burgos','No','Yes'),
	array('Valladolid','Segovia','No','Yes'),
	array('Valladolid','Avila','No','Yes'),
	array('Valladolid','Salamanca','No','Yes'),
	array('Valladolid','Zamora','No','Yes'),
	array('Valladolid','Leon','No','Yes'),
	array('Segovia','Burgos','No','Yes'),
	array('Segovia','Soria','No','Yes'),
	array('Segovia','Guadalajara','No','Yes'),
	array('Segovia','Madrid','No','Yes'),
	array('Segovia','Avila','No','Yes'),
	array('Segovia','Valladolid','No','Yes'),
	array('Soria','Logrono','No','Yes'),
	array('Soria','Pamplona','No','Yes'),
	array('Soria','Zaragoza','No','Yes'),
	array('Soria','Guadalajara','No','Yes'),
	array('Soria','Segovia','No','Yes'),
	array('Soria','Burgos','No','Yes'),
	array('Zaragoza','Huesca','No','Yes'),
	array('Zaragoza','Lerida','No','Yes'),
	array('Zaragoza','Tarragona','No','Yes'),
	array('Zaragoza','Teruel','No','Yes'),
	array('Zaragoza','Guadalajara','No','Yes'),
	array('Zaragoza','Soria','No','Yes'),
	array('Zaragoza','Pamplona','No','Yes'),
	array('Tarragona','Lerida','No','Yes'),
	array('Tarragona','Barcelona','Yes','Yes'),
	array('Tarragona','Costa Catalana','Yes','No'),
	array('Tarragona','Castellon','Yes','Yes'),
	array('Tarragona','Teruel','No','Yes'),
	array('Tarragona','Zaragoza','No','Yes'),
	array('Avila','Valladolid','No','Yes'),
	array('Avila','Segovia','No','Yes'),
	array('Avila','Madrid','No','Yes'),
	array('Avila','Toledo','No','Yes'),
	array('Avila','Caceres','No','Yes'),
	array('Avila','Salamanca','No','Yes'),
	array('Madrid','Segovia','No','Yes'),
	array('Madrid','Guadalajara','No','Yes'),
	array('Madrid','Cuenca','No','Yes'),
	array('Madrid','Toledo','No','Yes'),
	array('Madrid','Avila','No','Yes'),
	array('Guadalajara','Soria','No','Yes'),
	array('Guadalajara','Zaragoza','No','Yes'),
	array('Guadalajara','Teruel','No','Yes'),
	array('Guadalajara','Cuenca','No','Yes'),
	array('Guadalajara','Madrid','No','Yes'),
	array('Guadalajara','Segovia','No','Yes'),
	array('Teruel','Zaragoza','No','Yes'),
	array('Teruel','Tarragona','No','Yes'),
	array('Teruel','Castellon','No','Yes'),
	array('Teruel','Valencia','No','Yes'),
	array('Teruel','Cuenca','No','Yes'),
	array('Teruel','Guadalajara','No','Yes'),
	array('Castellon','Costa Catalana','Yes','No'),
	array('Castellon','Levante','Yes','No'),
	array('Castellon','Tarragona','Yes','Yes'),
	array('Castellon','Valencia','Yes','Yes'),
	array('Castellon','Teruel','No','Yes'),
	array('Toledo','Madrid','No','Yes'),
	array('Toledo','Cuenca','No','Yes'),
	array('Toledo','Ciudad Real','No','Yes'),
	array('Toledo','Badajoz','No','Yes'),
	array('Toledo','Caceres','No','Yes'),
	array('Toledo','Avila','No','Yes'),
	array('Cuenca','Teruel','No','Yes'),
	array('Cuenca','Valencia','No','Yes'),
	array('Cuenca','Albacete','No','Yes'),
	array('Cuenca','Ciudad Real','No','Yes'),
	array('Cuenca','Toledo','No','Yes'),
	array('Cuenca','Madrid','No','Yes'),
	array('Cuenca','Guadalajara','No','Yes'),
	array('Valencia','Teruel','No','Yes'),
	array('Valencia','Castellon','Yes','Yes'),
	array('Valencia','Levante','Yes','No'),
	array('Valencia','Alicante','Yes','Yes'),
	array('Valencia','Albacete','No','Yes'),
	array('Valencia','Cuenca','No','Yes'),
	array('Ciudad Real','Toledo','No','Yes'),
	array('Ciudad Real','Cuenca','No','Yes'),
	array('Ciudad Real','Albacete','No','Yes'),
	array('Ciudad Real','Jaen','No','Yes'),
	array('Ciudad Real','Cordoba','No','Yes'),
	array('Ciudad Real','Badajoz','No','Yes'),
	array('Albacete','Cuenca','No','Yes'),
	array('Albacete','Valencia','No','Yes'),
	array('Albacete','Alicante','No','Yes'),
	array('Albacete','Murcia','No','Yes'),
	array('Albacete','Granada','No','Yes'),
	array('Albacete','Jaen','No','Yes'),
	array('Albacete','Ciudad Real','No','Yes'),
	array('Alicante','Valencia','Yes','Yes'),
	array('Alicante','Levante','Yes','No'),
	array('Alicante','Mediterraneo Sur','Yes','No'),
	array('Alicante','Murcia','Yes','Yes'),
	array('Alicante','Albacete','No','Yes'),
	array('Cordoba','Ciudad Real','No','Yes'),
	array('Cordoba','Jaen','No','Yes'),
	array('Cordoba','Granada','No','Yes'),
	array('Cordoba','Malaga','No','Yes'),
	array('Cordoba','Sevilla','No','Yes'),
	array('Cordoba','Badajoz','No','Yes'),
	array('Jaen','Ciudad Real','No','Yes'),
	array('Jaen','Albacete','No','Yes'),
	array('Jaen','Granada','No','Yes'),
	array('Jaen','Cordoba','No','Yes'),
	array('Murcia','Alicante','Yes','Yes'),
	array('Murcia','Mediterraneo Sur','Yes','No'),
	array('Murcia','Almeria','Yes','Yes'),
	array('Murcia','Granada','No','Yes'),
	array('Murcia','Albacete','No','Yes'),
	array('Sevilla','Cordoba','No','Yes'),
	array('Sevilla','Malaga','No','Yes'),
	array('Sevilla','Cadiz','No','Yes'),
	array('Sevilla','Huelva','No','Yes'),
	array('Sevilla','Badajoz','No','Yes'),
	array('Cadiz','Sevilla','No','Yes'),
	array('Cadiz','Malaga','Yes','Yes'),
	array('Cadiz','Huelva','Yes','Yes'),
	array('Cadiz','Estrecho de Gibraltar','Yes','No'),
	array('Cadiz','Mediterraneo Sur','Yes','No'),
	array('Cadiz','Atlantico Sur','Yes','No'),
	array('Malaga','Cordoba','No','Yes'),
	array('Malaga','Granada','Yes','Yes'),
	array('Malaga','Cadiz','Yes','Yes'),
	array('Malaga','Sevilla','No','Yes'),
	array('Malaga','Mediterraneo Sur','Yes','No'),
	array('Granada','Jaen','No','Yes'),
	array('Granada','Albacete','No','Yes'),
	array('Granada','Murcia','No','Yes'),
	array('Granada','Almeria','Yes','Yes'),
	array('Granada','Mediterraneo Sur','Yes','No'),
	array('Granada','Malaga','Yes','Yes'),
	array('Granada','Cordoba','No','Yes'),
	array('Almeria','Murcia','Yes','Yes'),
	array('Almeria','Granada','Yes','Yes'),
	array('Almeria','Mediterraneo Sur','Yes','No'),
	array('Argelia','Mediterraneo Sur','Yes','No'),
	array('Argelia','Levante','Yes','No'),
	array('Argelia','Melilla','Yes','No'),
	array('Portugal','Atlantico Norte','Yes','No'),
	array('Portugal','Atlantico Sur','Yes','No'),
	array('Portugal','Pontevedra','Yes','No'),
	array('Portugal','Huelva','Yes','No'),
	array('Francia Costa Oeste','Cantabrico','Yes','No'),
	array('Francia Costa Oeste','Golfo de Vizcaya','Yes','No'),
	array('Francia Costa Oeste','Donostia','Yes','No'),
	array('Francia Costa Este','Gerona','Yes','No'),
	array('Francia Costa Este','Mediterraneo Norte','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
